name: 'Download Release Asset'
description: 'An Action to download a release asset via GitHub Release API'
author: 'Colby Williams'
inputs:
  repository:
    description: 'Repository name with owner. For example, colbylwilliams/download-release-asset'
    required: false
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the asset.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
  tag:
    description: >
      The tag name of the release the asset is on. For example v1.0.0.


      This is required if the action was not triggered by a release event, whereas the release object in the event payload will be used.
    required: false
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the asset.'
    required: false
  asset:
    description: 'The name of the asset to download, including the extention. For example MyFile.zip'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
