name: "Download Release Asset"
description: "An Action to download a release asset via GitHub Release API"
author: "Colby Williams"
inputs:
  asset_id:
    description: "The ID of the uploaded asset to download"
    required: true
  file_path:
    description: "The path of the directory to save the downloaded asset"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "package"
  color: "gray-dark"
