name: "Download Release Asset"
description: "An Action to download a release asset via GitHub Release API"
author: "Colby Williams"
inputs:
  token:
    description: "The access token to access GitHub with"
    required: true
    default: ""
  asset_id:
    description: "The ID of the uploaded asset to download"
    required: true
  file_path:
    description: "The path of the directory to save the downloaded asset"
    required: true
  owner:
    description: "The owner of the repository"
    required: false
  repo:
    description: "The name of the repository"
    required: false
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "package"
  color: "gray-dark"
